In [4]:
import numpy
import pandas

In [5]:
import tensorflow as tf

In [6]:
mnist = tf.keras.datasets.mnist

https://www.tensorflow.org/tutorials/quickstart/beginner is the link for this copy pasta

In [7]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-1.0321428 ,  0.16997795,  0.47378558,  0.59880555, -0.61159575,
         0.15950716, -0.5767722 ,  0.19967166,  0.5828272 ,  0.21432891]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.03098901, 0.10310555, 0.13970889, 0.15831406, 0.04718988,
        0.10203159, 0.04886215, 0.10621305, 0.15580457, 0.10778131]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.2824728

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2980 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1424 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1078 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0857 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 2s 982us/step - loss: 0.0750 - accuracy: 0.9769


In [16]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0696 - accuracy: 0.9774 - 744ms/epoch - 2ms/step


[0.06955474615097046, 0.977400004863739]

In [17]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8022261e-08, 5.2602628e-10, 5.1353431e-06, 1.4478127e-03,
        9.2186302e-12, 3.1313994e-07, 8.1350367e-13, 9.9853551e-01,
        1.6292289e-06, 9.5209562e-06],
       [4.2577983e-11, 6.8225363e-06, 9.9998915e-01, 3.9832521e-06,
        7.9834428e-16, 1.2578313e-09, 5.4227889e-10, 1.0231070e-13,
        8.8748866e-09, 1.4781757e-15],
       [5.9079133e-07, 9.9803323e-01, 2.6077358e-04, 1.2057415e-05,
        2.3301263e-05, 2.4203209e-06, 1.1263350e-05, 9.7163027e-04,
        6.8409130e-04, 7.2665671e-07],
       [9.9815208e-01, 1.7192998e-06, 8.5664575e-04, 2.5252296e-04,
        3.1759221e-08, 5.2035874e-04, 3.2886630e-05, 1.1867419e-04,
        1.6302427e-06, 6.3436724e-05],
       [6.4272490e-06, 5.7664464e-09, 5.4277749e-05, 4.6059301e-07,
        9.9705052e-01, 6.8887407e-06, 3.1111300e-05, 7.8025310e-05,
        3.9717837e-05, 2.7326921e-03]], dtype=float32)>

# ML Zero to Hero by TensorFlow on Youtube

In [1]:
import tensorflow as tf

In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist

In [3]:
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

In [7]:
# model.compile(optimizer=tf.train.AdamOptimizer(),
#              loss='sparse_categorical_crossentropy')
# not applicable to V2 of tensorflow


model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy')

In [8]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 934us/step - loss: 2.6745
Epoch 2/5
1875/1875 [==============================] - 2s 892us/step - loss: 0.6448
Epoch 3/5
1875/1875 [==============================] - 2s 952us/step - loss: 0.5707
Epoch 4/5
1875/1875 [==============================] - 2s 904us/step - loss: 0.5346
Epoch 5/5
1875/1875 [==============================] - 2s 803us/step - loss: 0.5179


In [11]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 704us/step - loss: 0.5555


0.5554860830307007

## Video 3

In [1]:
import tensorflow as tf
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [30]:
model = tf.keras.models.Sequential([
    # 64 filters applied to the convolutional NN
    tf.keras.layers.Conv2D(64, (3,3), activation='relu',
                          input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D(2,2),
    # you can stack convolutional layers, remove input shape
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)
])

In [ ]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy')
model.fit(train_images, train_labels, epochs=5)
print(model.metrics_names)
model.evaluate(test_images, test_labels)
# 0.368 from the video
# 0.291 with 2 extra dense layers
# 2.303 if you add a second soft max layer
# 0.395 if you add another filtering layers

Epoch 1/5
1875/1875 [==============================] - 25s 13ms/step - loss: 0.6670
Epoch 2/5
1875/1875 [==============================] - 26s 14ms/step - loss: 0.3765
Epoch 3/5
 210/1875 [==>...........................] - ETA: 22s - loss: 0.3334